class City {
  final String name;

  City(this.name);
}

List<City> cities = [
  City('Hà Nội'),
  City('TP. Hồ Chí Minh'),
  City('Bắc Giang'),
  City('Bắc Ninh'),
  City('Bình Dương'),
  City('Đà Nẵng'),
  City('Hải Dương'),
  City('Hưng Yên'),
  City('Long An'),
  City('Tiền Giang'),
  City('An Giang'),
  City('Bà Rịa - Vũng Tàu'),
  City('Bắc Kạn'),
  City('Bạc Liêu'),
  City('Bến Tre'),
  City('Bình Định'),
  City('Bình Phước'),
  City('Bình Thuận'),
  City('Cà Mau'),
  City('Cần Thơ'),
  City('Cao Bằng'),
  City('Đắk Lắk'),
  City('Đắk Nông'),
  City('Điện Biên'),
  City('Đồng Nai'),
  City('Đồng Tháp'),
  City('Gia Lai'),
  City('Hà Giang'),
  City('Hà Nam'),
  City('Hà Tĩnh'),
  City('Hải Phòng'),
  City('Hậu Giang'),
  City('Hòa Bình'),
  City('Khánh Hòa'),
  City('Kiên Giang'),
  City('Kon Tum'),
  City('Lai Châu'),
  City('Lâm Đồng'),
  City('Lạng Sơn'),
  City('Lào Cai'),
  City('Nam Định'),
  City('Nghệ An'),
  City('Ninh Bình'),
  City('Ninh Thuận'),
  City('Phú Thọ'),
  City('Phú Yên'),
  City('Quảng Bình'),
  City('Quảng Nam'),
  City('Quảng Ngãi'),
  City('Quảng Ninh'),
  City('Quảng Trị'),
  City('Sóc Trăng'),
  City('Sơn La'),
  City('Tây Ninh'),
  City('Thái Bình'),
  City('Thái Nguyên'),
  City('Thanh Hóa'),
  City('Thừa Thiên Huế'),
];
