class City {
  final String name;

  City(this.name);
}

List<City> cities = [
  City('Hanoi'),
  City('Ho Chi Minh City'),
  City('New York'),
  City('Los Angeles'),
  City('London'),
  City('Paris'),
  City('Tokyo'),
  City('Seoul'),
  City('Beijing'),  
  City('Shanghai'),
  City('Moscow'),
  City('Ha Nam'),
  City('Berlin'),
  City('Madrid'),
  City('Rome'),
  City('Sydney'),
  City('Melbourne'),
  City('Cairo'),
  City('Cape Town'),
  City('Rio de Janeiro'),
  City('Buenos Aires'),
  City('Mexico City'),
  City('Toronto'),
  City('Vancouver'),
  City('Montreal'),
  City('Chicago'),
  City('Houston'),
  City('Dallas'),
  City('Philadelphia'),
  City('Phoenix'),
  City('San Antonio'),
  City('San Diego'),
  City('San Jose'),
  City('Jacksonville'),
  City('Indianapolis'),
  City('San Francisco'),
  City('Austin'),
  City('Columbus'),
  City('Fort Worth'),
  City('Charlotte'),
  City('Detroit'),
  City('El Paso'),
  City('Memphis'),
  City('Baltimore'),
  City('Boston'),
  City('Seattle'),
  City('Washington'),
  City('Nashville'),
  City('Denver'),
  City('Louisville'),
  City('Milwaukee'),
  City('Portland'),
  City('Las Vegas'),
  City('Oklahoma City'),
  City('Albuquerque'),
  City('Tucson'),
  City('ninh binh'),
  City('Hue'),
  City('Da Nang'),
  City('Hoi An'),
  City('Nha Trang'),
  City('Da Lat'),
  City('Phan Thiet'),
  City('Vung Tau'),
  City('Can Tho'),
  City('Phu Quoc'),
  City('Ha Long'),
  City('Sapa'),
  City('Hai Phong'),
  City('Quang tri'),
  City('Quang Binh'),
  City('Quang Nam'),
  City('Quang Ngai'),
  City('Binh Dinh'),
  City('Khanh Hoa'),
  City('Ninh Thuan'),
  City('Binh Thuan'),
  City('Kon Tum'),
  City('Gia Lai'),
  City('Dak Lak'),
  
  // add more cities here
];
